import { network } from "hardhat";
import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const { ethers } = await network.connect();

interface ContractDeclaration {
  /** Solidity 合约名（也是 ABI 文件名和 artifacts 目录名） */
  contract: string;
  /** 构造函数参数，可引用之前已部署合约的地址（用 $ContractName 占位） */
  args?: (string | `$${string}`)[];
}

const DECLARATIONS: ContractDeclaration[] = [
  { contract: "DigitalAssetNFT" },
  { contract: "FixedPriceMarket", args: ["$DigitalAssetNFT"] },
];

const ABI_DIRS = [
  resolve("../frontend/src/abis"),
  resolve("../indexer/src/abis"),
];

async function main() {
  const [deployer] = await ethers.getSigners();
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log(`deployer: ${deployer.address} (${ethers.formatEther(balance)} ETH)\n`);

  const addresses: Record<string, string> = {};

  for (const decl of DECLARATIONS) {
    const resolvedArgs = (decl.args ?? []).map((arg) =>
      typeof arg === "string" && arg.startsWith("$")
        ? addresses[arg.slice(1)]
        : arg
    );

    const c = await ethers.deployContract(decl.contract, resolvedArgs);
    await c.waitForDeployment();
    addresses[decl.contract] = await c.getAddress();
    console.log(`${decl.contract.padEnd(20)} ${addresses[decl.contract]}`);
  }

  syncABIs(addresses);
  writeConfig(addresses);
  writeIndexerEnv(addresses);
}

function writeIndexerEnv(addresses: Record<string, string>) {
  const envPath = resolve("../indexer/.env");
  const addr = (name: string) => addresses[name] ?? "";

  const lines = [
    `# Auto-generated by scripts/deploy.ts`,
    `RPC_URL=http://127.0.0.1:8545`,
    `NFT_ADDRESS=${addr("DigitalAssetNFT")}`,
    `FIXED_PRICE_ADDRESS=${addr("FixedPriceMarket")}`,
  ];
  if (addresses["OfferMarket"]) {
    lines.push(`OFFER_ADDRESS=${addr("OfferMarket")}`);
  }

  writeFileSync(envPath, lines.join("\n") + "\n");
  console.log(`indexer .env written: ${envPath}`);
}

function writeConfig(addresses: Record<string, string>) {
  const configPath = resolve("../frontend/src/config/contract.ts");

  const addr = (name: string) => addresses[name] ?? "0x0000000000000000000000000000000000000000";

  const content = [
    `// Auto-generated by scripts/deploy.ts — do not edit manually.`,
    ``,
    `export const NFT_ADDRESS = "${addr("DigitalAssetNFT")}";`,
    `export const FIXED_PRICE_ADDRESS = "${addr("FixedPriceMarket")}";`,
    `export const OFFER_ADDRESS = "${addr("OfferMarket")}";`,
    ``,
    `export const POLYGON_AMOY_CHAIN_ID = 80002;`,
    ``,
    `export const SUPPORTED_NETWORKS: Record<number, { name: string; rpcUrl: string; blockExplorer: string }> = {`,
    `  80002: {`,
    `    name: "Polygon Amoy Testnet",`,
    `    rpcUrl: "https://rpc-amoy.polygon.technology/",`,
    `    blockExplorer: "https://amoy.polygonscan.com",`,
    `  },`,
    `  11155111: {`,
    `    name: "Sepolia Testnet",`,
    `    rpcUrl: "https://sepolia.infura.io/v3/",`,
    `    blockExplorer: "https://sepolia.etherscan.io",`,
    `  },`,
    `  31337: {`,
    `    name: "Hardhat Local",`,
    `    rpcUrl: "http://127.0.0.1:8545",`,
    `    blockExplorer: "",`,
    `  },`,
    `};`,
    ``,
  ].join("\n");

  writeFileSync(configPath, content);
  console.log(`config written: ${configPath}`);
}

function syncABIs(addresses: Record<string, string>) {
  const artifactsDir = resolve("artifacts/contracts");

  for (const name of Object.keys(addresses)) {
    const src = resolve(artifactsDir, `${name}.sol/${name}.json`);
    try {
      const abi = JSON.parse(readFileSync(src, "utf-8")).abi;
      for (const dst of ABI_DIRS) {
        mkdirSync(dst, { recursive: true });
        writeFileSync(resolve(dst, `${name}.json`), JSON.stringify({ abi }, null, 2));
      }
    } catch {
      console.warn(`  skip ABI: ${name}.json not found`);
    }
  }
  console.log(`\nABI synced: frontend/src/abis/ + indexer/src/abis/`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
