import { mkdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { config } from "hardhat";

export interface ContractDeclaration {
  contract: string;
  args?: (string | `$${string}`)[];
}

const ABI_DIRS = [
  resolve("../frontend/src/abis"),
  resolve("../indexer/src/abis"),
];

export function saveDeployment(
  networkName: string,
  addresses: Record<string, string>,
) {
  const dir = resolve("deployments");
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    resolve(dir, `${networkName}.json`),
    JSON.stringify(addresses, null, 2),
  );
  console.log(`deployment saved: deployments/${networkName}.json`);
}

export function loadDeployment(
  networkName: string,
): Record<string, string> {
  const path = resolve("deployments", `${networkName}.json`);
  if (!existsSync(path)) {
    throw new Error(
      `No deployment found for network "${networkName}". ` +
        `Run scripts/deploy.ts first or check deployments/${networkName}.json`,
    );
  }
  return JSON.parse(readFileSync(path, "utf-8"));
}

export function syncABIs(addresses: Record<string, string>) {
  const artifactsDir = resolve("artifacts/contracts");

  for (const name of Object.keys(addresses)) {
    const src = resolve(artifactsDir, `${name}.sol/${name}.json`);
    try {
      const abi = JSON.parse(readFileSync(src, "utf-8")).abi;
      for (const dst of ABI_DIRS) {
        mkdirSync(dst, { recursive: true });
        writeFileSync(resolve(dst, `${name}.json`), JSON.stringify({ abi }, null, 2));
      }
    } catch {
      console.warn(`  skip ABI: ${name}.json not found`);
    }
  }
  console.log(`ABI synced: frontend/src/abis/ + indexer/src/abis/`);
}

export async function writeFrontendConfig(
  addresses: Record<string, string>,
  networkName: string,
) {
  const configPath = resolve("../frontend/src/config/contract.ts");
  mkdirSync(dirname(configPath), { recursive: true });
  const addr = (name: string) =>
    addresses[name] ?? "0x0000000000000000000000000000000000000000";

  const content = [
    `// Auto-generated — do not edit manually.`,
    `// Last deployment network: ${networkName}`,
    ``,
    `export const NFT_ADDRESS = "${addr("DigitalAssetNFT")}";`,
    `export const FIXED_PRICE_ADDRESS = "${addr("FixedPriceMarket")}";`,
    `export const OFFER_ADDRESS = "${addr("OfferMarket")}";`,
    ``,
  ].join("\n");

  writeFileSync(configPath, content);
  console.log(`config written: ${configPath}`);
}

export async function writeIndexerEnv(
  addresses: Record<string, string>,
  networkName: string,
) {
  const envPath = resolve("../indexer/.env");
  const addr = (name: string) => addresses[name] ?? "";

  const netConfig = config.networks[networkName];
  const rpcUrl =
    netConfig?.type === "http"
      ? await (netConfig as { url: { getUrl: () => Promise<string> } }).url.getUrl()
      : "http://127.0.0.1:8545";

  const lines = [
    `# Auto-generated by scripts/export.ts`,
    `RPC_URL=${rpcUrl}`,
    `NFT_ADDRESS=${addr("DigitalAssetNFT")}`,
    `FIXED_PRICE_ADDRESS=${addr("FixedPriceMarket")}`,
  ];
  if (addresses["OfferMarket"]) {
    lines.push(`OFFER_ADDRESS=${addr("OfferMarket")}`);
  }

  mkdirSync(dirname(envPath), { recursive: true });
  writeFileSync(envPath, lines.join("\n") + "\n");
  console.log(`indexer .env written: ${envPath}`);
}
