// Auto-generated by scripts/deploy.ts — do not edit manually.

export const NFT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
export const FIXED_PRICE_ADDRESS = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512";
export const OFFER_ADDRESS = "0x0000000000000000000000000000000000000000";

export const POLYGON_AMOY_CHAIN_ID = 80002;

export const SUPPORTED_NETWORKS: Record<number, { name: string; rpcUrl: string; blockExplorer: string }> = {
  80002: {
    name: "Polygon Amoy Testnet",
    rpcUrl: "https://rpc-amoy.polygon.technology/",
    blockExplorer: "https://amoy.polygonscan.com",
  },
  11155111: {
    name: "Sepolia Testnet",
    rpcUrl: "https://sepolia.infura.io/v3/",
    blockExplorer: "https://sepolia.etherscan.io",
  },
  31337: {
    name: "Hardhat Local",
    rpcUrl: "http://127.0.0.1:8545",
    blockExplorer: "",
  },
};
